strategy:
  matrix:
    windows:
      image: 'windows-latest'
      standard: 'netstandard2.0'
    mac:
      image: 'macos-latest'
      standard: 'netstandard2.0'
    linux:
      image: 'ubuntu-latest'
      standard: 'netstandard2.0'

pool:
  vmImage: $(image)

steps:
  - task: UseDotNet@2
    displayName: Install
    inputs:
      version: '2.x'
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '**/Pfim.csproj'
      arguments: -f $(standard)
  - task: DotNetCoreCLI@2
    displayName: ImageSharp Sample Build
    inputs:
      command: build
      projects: '**/Pfim.ImageSharp.csproj'
  - task: DotNetCoreCLI@2
    displayName: Skia Sample Build
    inputs:
      command: build
      projects: '**/Pfim.Skia.csproj'
  - task: DotNetCoreCLI@2
    displayName: Windows Test
    condition: eq(variables['image'], 'windows-latest')
    inputs:
      command: test
      projects: '**/*Tests.csproj'
      arguments: '-f netcoreapp2.0 --collect "Code coverage"'
  - task: DotNetCoreCLI@2
    displayName: Test
    condition: ne(variables['image'], 'windows-latest')
    inputs:
      command: test
      projects: '**/*Tests.csproj'
      arguments: '-f netcoreapp2.0'
      publishTestResults: false
